### ISSUE TITLE
[함수형 프로그래밍] Chapter3.함수적 자료구조

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#10]

**Comment by iknowchang** [comment]
# 함수형프로그래밍_함수적 자료구조
## 목표
* 함수적 자료구조(functional data structure)가 무엇인지 설명한다
* 패턴 부합이 무엇인지 익힌다.
* 순수 함수 작성과 일반화를 익힌다.

**Comment by iknowchang** [comment]
## 함수적 자료구조의 정의
* immutable(불변)이다.
* 여분의 복사가 많이 일어날 것으로 생각하지만, 그렇지 않다.
* 단일 연결 목록(singly linked list)를 통해 살펴 본다
```
package fpinscala.datastructures

// sealed : 이 특질의 모든 구현이 반드시 이 파일 안에 선언되어야함
// trait : 추상인터페이스
sealed trait List[+A]
// 자료 생성자1
// Nil로 표기된 빈 목록일 수 있음
case object Nil extends List[Nothing]
// 자료 생성자2
// 자료 생성자 Cons로 표기되는 Non-empty 목록일 수 있음
// +A 를 넣어서 polymorphic이 될 수 있음. Int, Double...
case class Cons[+A](head:A, tail:List[A]) extends List[A]

// List 동반객체
object List {
    def sum(ints: List[Int]): Int= ints match {
        case Nil => 0  // 빈 목록의 합은 0.
        case Cons(x, xs)=> x+sum(xs) // x로 시작하는 목록의 합은 x더하기 나머지
    }
    def product(ds:List[Double]):Double = ds match {
        case Nil => 1.0
        case Cons(0.0,_)=>0.0
        case Cons(x,xs)=>x*product(xs)
    }
    def apply[A](as:a*):List[A]=
        if(as.isEmpty) Nil
        else Cons(as.head, apply(as.tail:_*))
}
```
[예제를 통한 이해 링크](https://scalafiddle.io/sf/t19gifO/0)

**실행코드**
```
val ex1:List[Double]=Nil
val ex2:List[Int]=Cons(1,Nil)
val ex3:List[String]=Cons("a", Cons("b",Nil))

println(ex1);
println(ex2);
println(ex3);
```
**결과 값**
```
Nil
Cons(1,Nil)
Cons(a,Cons(b,Nil))
```
### appendix : 공변과 불변에 대해
`sealed trait List[+A]`에서 +는 A가 List의 공변(convariant)매개 변수임을 뜻하는 가변 지정다(variance annotation)이다.
예) Dog is subtype of Animal, then List[Dog] is subtype of List[Animal]
=> List[Nothing] is subtype of any List[?] because Nothing is subtype of any ?

**Comment by iknowchang** [comment]
## 패턴 부합
* 패턴 부합 개념에 대해 알아본다.
* sum, product를 동반 객체(companion object)라 부른다. 이 두 함수는 패턴 부합을 활용해 구현되어 있음.

    def sum(ints: List[Int]): Int= ints **match** {
        **case** Nil => 0  
        **case** Cons(x, xs)=> x+sum(xs) // 재귀적
    }
    def product(ds:List[Double]):Double = ds **match** {
        **case** Nil => 1.0
        **case** Cons(0.0,_)=>0.0
        **case** Cons(x,xs)=>x*product(xs) // 재귀적
    }

* 예제를 통한 학습
<details><summary>List(1,2,3) match {case _ => 42 }</summary>
<p>
4
</p>
</details>

<details><summary>List(1,2,3) match {case Cons(h,_) => h}</summary>
<p>
1
</p>
</details>

<details><summary>List(1,2,3) match {case Cons(_,t) => t}</summary>
<p>
Cons(2,Cons(3,Nil))
</p>
</details>

<details><summary>List(1,2,3) match {case Nil => 42}</summary>
<p>
ERROR: undefined
Error
</p>
</details>

[실행 코드](https://scalafiddle.io/sf/RmA9l0P/0)

* 연습문제 3.1 : 다음 패턴 부합 표현식의 결과는?
```
 val x=List(1,2,3,4,5) match {
            case Cons(x, Cons(2,Cons(4,_))) => x
            case Nil => 42
            case Cons(x,Cons(y, Cons(3, Cons(4,_)))) => x+y
            case Cons(h,t) => h+sum(t)  // h+sum(t) // error: not found: value sum
            case _ => 101
        }
```
<details><summary>정답 보기</summary>
<p>
3 <br>
 // 1. Cons(x,Cons(y, Cons(3, Cons(4,_)))) => x+y 에 의해 1+2=3
</p>
</details>

[실행 코드](https://scalafiddle.io/sf/RQaowl0/0)

### Appendix : 가변 인수 함수
`List(1,2,3)` 같은 코드가 어떻게 가능할까? 
```
      def apply[A](as:A*):List[A]=
        if(as.isEmpty) Nil
        else Cons(as.head, apply(as.tail:_*))
```
* apply는 가변 인수 함수임 (: A형식의 인수 0개 이상 받을 수 있음)
* 인스턴스를 편리하게 생성하기 위해, 관례적으로 apply 를 동반 객체에 만듬

**Comment by iknowchang** [comment]
## 함수적 자료구조의 자료 공유
불변인데 어떻게 요소를 추가하거나 삭제를 할까?  이 방법을 배운다.

**목록에 요소를 추가하려면?**
* 기존 목록 xs에 1 추가 하는 상황
* Cons(1,xs) 라는 새 목록 만든다. <= 자료 공유 (data sharing)
* 복사본 만들 필요 없음

**목록 mylist=Cons(x,xs) 의 앞 요소 제거하려면**
* 그냥 xs 반환한다.  <= 영속성(persistent) : 기존, 신규 목록 둘다 사용 가능


#### 연습문제 3.2 : List의 첫 요소를 제거하는 tail을 구현하라
<details><summary>정답 보기</summary>
<p>
    def tail[A](l:List[A]): List[A] = l match {
      case Nil => sys.error("tail of empty list")
      case Cons(_,t) => t
    }

// println(List.tail(List(1,2,3,4,5)))
// => Cons(2,Cons(3,Cons(4,Cons(5,Nil))))
</p>
</details>

[실행 코드](https://scalafiddle.io/sf/BzTMdbj/0)

#### 연습문제 3.3 : List 첫 요소를 다른 값으로 대체하는 함수 setHead 구현
<details><summary>정답 보기</summary>
<p>
    def setHead[A](l:List[A], h:A): List[A] = l match {
        case Nil => sys.error("setHead on empty list")
        case Cons(_,t) => Cons(h,t)
    }

println(List.setHead(List(1,2,3,4,5),6))
=> Cons(6,Cons(2,Cons(3,Cons(4,Cons(5,Nil)))))
</p>
</details>

[실행 코드](https://scalafiddle.io/sf/I0nMJSs/0)

### 자료 공유의 효용성
자료 공유를 활용하면 연산을 보다 효율적으로 할 수 있음. 아래는 예제를 통한 학습

#### 연습문제 3.4 : tail을 일반화하여 목록에서 처음 n개의 요소를 제거하는 함수 drop 구현
<details><summary>정답 보기</summary>
<p>
 def drop[A](l:List[A], n:Int): List[A] =  {
        var tmp=l
        var m=n
        while(m>0) {
            m=m-1
            tmp=List.tail(tmp)
        }
        tmp
    }

//  책 답
def drop[A](l: List[A], n: Int): List[A] =
    if (n <= 0) l
    else l match {
      case Nil => Nil
      case Cons(_,t) => drop(t, n-1)
    }
// println(List.drop(List(1,2,3,4,5),2))
// => Cons(3,Cons(4,Cons(5,Nil)))
</p>
</details>
[실행 코드](https://scalafiddle.io/sf/k1IaEUY/0)


#### 연습문제 3.5 : 주어진 술어(predicate)와 부합하는 List의 앞 요소들(prefix)를 제거하는 함수 구현
<details><summary>정답 보기</summary>
<p>
 def dropWhile[A](l:List[A], f:A=>Boolean): List[A] =  {
        l match {
          case Cons(h,t) if f(h) => dropWhile(t, f)
          case _ => l
        }
    }

// println(List.dropWhile(List(1,1,3,4,5),(x:Int)=>x==1))
// => Cons(3,Cons(4,Cons(5,Nil)))
</p>
</details>

[실행 코드](https://scalafiddle.io/sf/oxr8a1z/0)

한 목록의 모든 요소를 다른 목록의 끝에 추가
* a1 만큼만 복사 발생. 
* 나머지는 a2를 가리키기만 한다. 
```
def append[A](a1:List[A], a2:List[A]): List[A] = a1 match {
        case Nil => a2
        case Cons(h,t)=>Cons(h, append(t,a2))
    }

// println(List.append(List(1,2),List(3,4)))
// => Cons(1,Cons(2,Cons(3,Cons(4,Nil))))
```

#### 연습문제 3.6 : 마지막 요소를 제외한 모든 요소의 List return 함수를 만든다. 이 함수가 효율적이지 않은 이유도 설명한다. 
`def init[A](l:List[A]` 
<details><summary>정답 보기</summary>
<p>
def init[A](l:List[A]):List[A] = l match {
        case Nil => Nil
        case Cons(h,Nil) => Nil
        case Cons(h,t)=>Cons(h,init(t))
    }

// println(List.init(List(1,2,3,4,5)))
// => Cons(1,Cons(2,Cons(3,Cons(4,Nil))))
// 계속 이전의 모든 객체를 복사해야한다. 
</p>
</details>

### 고차 함수를 위한 형식 추론 개선
기존버전의 dropWhile은 익명 함수의 인수의 형식을 꼭 명시해야한다. 
```
 def dropWhile[A](l:List[A], f:A=>Boolean): List[A] =  {
        l match {
          case Cons(h,t) if f(h) => dropWhile(t, f)
          case _ => l
        }
    }

println(List.dropWhile(List(1,1,3,4,5),(x:Int)=>x==1))
println(List.dropWhile(List(1,1,3,4,5),x=>x==1)) // ScalaFiddle.scala:19: error: missing parameter type
```
[실행 코드](https://scalafiddle.io/sf/iStZvgF/0)

인수를 두 그룹으로 묶으면 스칼라는 추론할 수 있다.
```
sealed trait List[+A]
case object Nil extends List[Nothing]
case class Cons[+A](head:A, tail:List[A]) extends List[A]

object List {
      def apply[A](as:A*):List[A]=
        if(as.isEmpty) Nil
        else Cons(as.head, apply(as.tail:_*))
        
      def dropWhile[A](l:List[A])(f:A=>Boolean): List[A] =  {
        l match {
          case Cons(h,t) if f(h) => dropWhile(t)(f)
          case _ => l
        }
      }
}

println(List.dropWhile(List(1,1,3,4,5))((x:Int)=>x==1))
println(List.dropWhile(List(1,1,3,4,5))(x=>x==1))
```

dropWhile(ws)(f) 형태가 된다. dropWhile(ws)는 하나의 함수를 돌려주며, 그 함수가 인수가 되면서 f로 호출한다. 
[실행 코드](https://scalafiddle.io/sf/iStZvgF/1)

**Comment by iknowchang** [comment]
답안 
[fpinscala/List.scala at master · fpinscala/fpinscala · GitHub](https://github.com/fpinscala/fpinscala/blob/master/answers/src/main/scala/fpinscala/datastructures/List.scala)

**Comment by iknowchang** [comment]
## 목록에 대한 재귀와 고차 함수로의 일반화
sum, product를 보면 정의가 아주 비슷함
```
    def sum(ints: List[Int]): Int= ints match {
        case Nil => 0  // 빈 목록의 합은 0.
        case Cons(x, xs)=> x+sum(xs) // x로 시작하는 목록의 합은 x더하기 나머지
    }
    def product(ds:List[Double]):Double = ds match {
        case Nil => 1.0
        case Cons(0.0,_)=>0.0
        case Cons(x,xs)=>x*product(xs)
    }
```

부분 표현식을 추출하여 함수 인수로 대체 가능함
```
    def foldRight[A,B](as:List[A], z:B)(f:(A,B)=>B):B=
      as match {
        case Nil=>z
        case Cons(x, xs)=>f(x,foldRight(xs,z)(f))
    }
    def sum2(ns:List[Int])=
      foldRight(ns,0)((x,y)=>x+y)
    def product2(ns:List[Double])=
      foldRight(ns,1.0)(_*_)   // _*_ 는 (x,y)=>x*y 와 같다
```
[코드 실행](https://scalafiddle.io/sf/t19gifO/3)

#### Appendix : 익명 함수를 위한 밑줄 표기법
스칼라가 형식을 추론할 수 있다면 익명 함수로 표기 가능
_ + _   는  (x,y)=>x+y
_ * 2   는  x=>x+2
_.head   는  xs=>xs.head
_ drop _   는  (xs,n)=>xs.drop(n)

_뒤의 연습 문제는 생략 T T_

**Comment by iknowchang** [comment]
## 트리
#### Appendix : 튜플 형식
```
val p=("bob", 1)
println(p)
println(p._1)
println(p._2)
println(p match {case(a,b)=>b})

(bob,1)
bob
1
1
```
[실행 코드](https://scalafiddle.io/sf/hrcZPxs/0)

#### 이진 트리 자료 구조 정의해 보자
```
sealed trait Tree[+A]
case class Leaf[A](value:A) extends Tree[A]
case class Branch[A](left:Tree[A], right:Tree[A]) extends Tree[A]
```
[트리 코드](https://scalafiddle.io/sf/Pmvb7sL/0)

#### 연습문제 3.25 : 트리의 노드 개수를 세는 함수 size를 작성하시오
[실행 코드](https://scalafiddle.io/sf/Pmvb7sL/2)

**Comment by iknowchang** [comment]
https://scalafiddle.io/sf/Pmvb7sL/1
