### ISSUE TITLE
[스칼라+플레이] Chapter5.함수 

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#4]

**Comment by enochyeon** [comment]
## 5.1 왜 함수형 언어인가?
* 자원(변수 등)에 대한 동시성 문제를 해결할 수 있는 방법으로 조명받음

## 5.2 스칼라의 함수
* 함수도 객체
* 함수들이 유연하게 여기저기 전달되고 끼워 맞춰 사용될 수 있도록
* 여러 작업 단위들이 서로 영향을 주지 않고, 함수 자신의 역할만 하면됨

## 5.3 함수 정의
* `Unit`은 자바의 `void`와 같음. (#1)
* 반환 자료형 생략 가능
* `return` 구문 생략 가능. 마지막 실행 값이 반환됨
  * 사용하는 경우 반환 자료형도 명시해야 함

## 5.4 CALL-BY-NAME
* 일반적인 호출 형태
  * call by value
  * call by name (call by reference를 의미하는 듯)
* 함수를 실행하는 것이 아니라 함수를 부른다는 뜻
* 스칼라에서 CALL-BY-NAME으로 호출되는 함수는, **호출하는 함수가 매개변수를 필요로 할 때마다 계속 부름을 당함**

## 5.5 함수의 일부 인수 고정하기(부분 적용 함수)
```scala
val fixedValueFunction = go(thisYear, _: String)
```
* `_`를 사용하여 변하는 것 표시

## 5.6 =>를 이용한 함수 표현식
* 함수 객체를 할당 받을 수 있는 표현식
* 함수표현식을 사용하여 다른 함수의 인자로 전달 가능

#### 코드 5-6 val 변수에 함수 넣기
```scala
object Ex_5_6 {
  def main(args: Array[String]): Unit = {
    val g = f _
    println(f(1))
  }

  def f(i: Int) = i
}
```

#### 코드 5-6의 다른 표현 방법
```scala
var g:(Int => Int) = f // 언더스코어를 사용하지 않음
```
```scala
val g = f // 언더스코어 사용하지 않으려면
def f = (i: Int) => i // f를 함수 표현식으로
```
* 명시적으로 함수가 기대되지 않는 곳에서 `=` 연산자를 이용해 매개변수가 필요한 함수를 대입
* `f`는 스칼라에서 말하는 함수 객체는 아님

## 5.7 함수 표현식의 예
```scala
def calc(f: Int => Int, start: Int, end: Int) = {}

calc(x => x * x, 2, 5)
calc(x => x + x, 1, 3)
```

## 5.8 매개변수가 여러 개인 함수
```scala
def printlnStrings(args: String*) = {
}

printlnStrings("a")
printlnStrings("a", "b")
printlnStrings("a", "b", "c")
```

## 5.9 매개변수의 기본값 설정
```scala
def default(a: Int = 4, b: Int = 5): Int = a + b
```

## 5.10 apply()
* 생성자 처럼 호출 가능
* 특정 메서드를 지정할 수 있음
```scala
something(2)
something.apply(2)
something.method(2)
```

## 5.11 implicit 함수
* 에러를 바로 내지 않고 해당하는 함수가 있으면 그것을 사용해서 암묵적으로 형 변환 하도록 함
* 장점 - 코드량 단축
* 단점 - 의도치 않은 형변환 수행됨
```scala
implicit def doubleToInd(d: Double) = d.toInt
val x: Int = 18.0 // <--- 컴파일 오류가 발생하지 않음
```

**Comment by bluewbear** [comment]
[Scala의 그 놈](https://charsyam.wordpress.com/2015/03/03/%EC%9E%85-%EA%B0%9C%EB%B0%9C-scala%EC%9D%98-%EA%B1%B0%EC%8B%9C%EA%B8%B0-_underscore-%EC%9D%98-%EC%9A%A9%EB%B2%95-%EC%A0%95%EB%A6%AC/)
