### ISSUE TITLE
[스칼라+플레이] Chapter6.패턴 매칭 

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#5]

**Comment by poporis** [comment]
### 기본 자료형 패턴 매칭
* match 예약어
* 언더바(_) : 모든 값을 뜻하는 와일드카드
    - 일치하지 않은 값 -> 런타임 에러 (반드시 쓰는 편이 좋음)
~~~scala
obj match {
    case x => println("x")
    case y => println("y")
    case _ => println("etc")
}
~~~

https://scastie.scala-lang.org/K9qPbDcFRdOtPUI9CdtVFw


* 패턴 매칭 함수
~~~scala
def matchFunction(intput: Any): Any = input match {
    case 100: =>"hundred" 
    case "hundred" => 100
    case etcNumber: Int => "입력값은 100이 아닌 Int형 정수입니다."
    case _ => "기타"
}
~~~

### 객체 패턴 매칭
* case class
~~~scala
case class Person(name: String, age: Int, rank: String)
~~~

* 와일드 카드 이용
~~~scala
case Person("김솔로", 27, _) => println("어 솔로 왔니?")
~~~

* 객체 변수값 사용
~~~scala
case Person("김솔로", 27, r) => println(r + "님이 입장하셨습니다.")
~~~

* case 문안에서 if 문
~~~scala
case Person(name, age, "사원") => 
    if (age > 25) println(name + " " + age  + "살이구나. 선 볼래?")

case Person(name, age, "사원") if (age > 25) => 
    println(name + " " + age  + "살이구나. 선 볼래?")
~~~

* 일치하지 않는 모든 기타 경우
~~~scala
case _ => println("매치되는 결과가 없습니다.")
~~~

https://scastie.scala-lang.org/YchZHVfQSvS9Z6ReX2ddZg

### extractor 패턴 매칭
 - 단순한 문자열이나 숫자 -> 문자열 가공하여 패턴 매칭
 - 추출자 (extractor) -> unapply() 메서드 구현을 통해 값을 검사 or 조작
 - 반환 자료형 : Option 형태 or Boolean
    - Some or true 이면 해당
    - None or false 이면 해당하지 않음
~~~scala
object Obj {
    def unapply(arg: String): Option[Int] = {}
}
~~~

https://scastie.scala-lang.org/VKGMFMsNQ3uStSefwIGmeA
