### ISSUE TITLE
[스칼라+플레이] Chapter7.컬렉션

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#6]

**Comment by bluewbear** [comment]
## 컬렉션?
- 여러 데이터들의 모음
 
## [배열](https://www.scala-lang.org/api/2.12.3/scala/Array.html)
- 가장 기본적인 자료 구조 
- 스칼라의 배열은 자바의 배열과 1:1 but! 조금 더 기능
```scala
// 기본적인 선언 
val array: Array[Int] = new Array[Int](10)
// 조금 더 생략된 선언 
val array = new Array[Int](10)
// apply() 메소드를 이용하여 값을 집어 넣으면서 선언 
val array = Array(13, 41, 52, 15, 222) // Array.apply()
// 혹은 String 자료형
val array = Array("a", "b", "c")
// 혹은 짬뽕
val array = Array(13, "hi", 1.43)
```
> 다차원 배열
> val matrix = Array.ofDim[Int](4, 5)
> print(matrix(3)(2))

## [리스트](https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/List.html)
- 제일 많이 사용하는 자료 구조, 중복 데이터 허용
- 배열과 비슷하지만 더 많은 기능을 포함
```scala
// 추상 클래스 혹은 이미 완성된 객체 형태로 존재하므로 new로 생성하지 않음! apply()!
val list = List()
// String 자료형 list 생성
val list: List[String] = List("a", "b", "c")
// 자료형 생략 가능
val list = List("a", "b", "c")
// cons(구성, Construction) operator를 사용하여 list 생성, 마지막 Nil은 필수
val list = "a" :: "b" :: "c" :: Nil 
// 리스트에서 꺼내오기
list(index) // java의 get method
// 빈 리스트 생성
val list: List[Int] = Nil // List()와 동일
```
> [Nil](https://www.scala-lang.org/api/2.12.3/scala/collection/immutable/Nil$.html)
> List를 상속, 아무것도 아닌 값을 뜻하며, 리스트의 끝을 가리킴

> ::: 연산자
> 두 리스트를 합친다.
> :: 는 리스트의 각 요소를 결합하고, :::는 여러 리스트를 병합 
> List.concat() 메소드와 동일, "++" 메소드도 동일 

## [맵](https://www.scala-lang.org/api/2.12.3/scala/collection/Map.html)
- key, value 쌍
```scala
val map = Map()
// 자료형을 명시
val map[Char, Int] = Map()
// 선언과 동시 초기 값 설정
val map = Map("key1" -> "value1", "key2" -> "value2, "key3 -> value3")
// 모든 키 가져오기
map.keys
// 모든 값 가져오기
map.values
// 맵이 비어있는지 체크
map.isEmpty
// 특정 키에 해당하는 값 가져오기
map("key1")
// 맵에 값 추가하기
map += ("key4" -> "value4")
// 맵에 값 삭제하기
map -= "key4"
```
> get(key)로 가져오기는 것도 가능
> 값을 꺼낼때 Option 객체에 자동 래핑이 되고 없으면 None을 반환
> but, apply()로 가져오는 경우 값이 없을 경우 예외 발생!

## [집합](https://www.scala-lang.org/api/2.12.3/scala/collection/Set.html)
- 중복되지 않는 값들 담기
```scala
// 자료형 명시해서 선언 
val set: Set[Int] = Set()
// 선언과 동시 값 추가
val set1 = Set ("a", "b", "c")
// set1에 "d" 요소를 추가하여 새로운 set2 만들기
val set2 = set1 + ("d")
```

## [튜플](https://www.scala-lang.org/api/2.12.3/scala/Tuple2.html)
- 여러 데이터를 하나의 묶음으로 처리
```scala
val number: Int
val name: String
(number, name)
```
- _1, _2
  - 튜플의 첫번째 값 "_1", 두번째 값 "_2"
- 3개의 객체를 담으면 `Tuple3` 클래스를 사용
  - `Tuple1` ~ `Tuple22`

## [옵션](https://www.scala-lang.org/api/2.12.3/scala/Option.html)
- "None"이거나 "Some()"을 하나 가지고 있음 -> 아무것도 가지고 있지 않거나 어떠한 값을 가지고 있는 상태
- Map에서 키를 이용하여 값을 가져올 때
  - 해당 값이 있다면 "Some()"
  - 값이 없으면 "None"
- 패턴 매칭 시 유용
```scala
object Ex_7_9 {
  def main(args: Array[String]): Unit = {
    val students = Map (1 -> "Tom", 2 -> "Kate", 3 -> "Ann")
    val one = students.get(1)
    val four = students.get(4)
    
    println(one)
    println(four)
    println(one.get)
    println(four.getOrElse("Nothing"))
  }
}
```
```scala
Some(Tom)
None
Tom
Nothing
```
> [None](https://www.scala-lang.org/api/2.12.3/scala/None$.html)
> 다른 언어의 null 값이 아니므로 NPE 방지!

## [시퀀스](https://www.scala-lang.org/api/2.12.3/scala/collection/Seq.html)
- 요소 간 순서가 있는 리스트
- 인덱싱 기능을 사용할려면 `zipWithIndex` 기능을 이용하여 tuple 형태로 이용해야 함. 
```scala
val data = Seq.range('a', 'e')
data.zipWithIndex //Vector((a,0), (b,1), (c,2), (d,3))
```
- [Scala Seq Example](https://alvinalexander.com/scala/seq-class-methods-examples-syntax)

## [이터레이터](https://www.scala-lang.org/api/2.12.3/scala/collection/Iterator.html)
- 컬렉션에서 데이터를 꺼내와서 차례로 무언가 처리를 할 때 사용
```scala
object Ex7_10 {
  def main(args: Array[String]): Unit = {
    val list = List("a", "b", "c")
    val iter = list.iterator
    while (iter.hasNext) {
      println(iter.next)
    }
  }
}
```
```
a
b
c
```

**Comment by enochyeon** [comment]
https://stackoverflow.com/questions/10866639/difference-between-a-seq-and-a-list-in-scala

**Comment by duckcalf** [comment]
list 관련 클래스 관계도
https://docs.scala-lang.org/tutorials/FAQ/collections.html
