### ISSUE TITLE
[스칼라+플레이] Chapter8.함수 컴비네이터 

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#7]

**Comment by gaepury** [comment]
## 함수 컴비네이터
- 구현된 로직에 따라 컬렉션을 변형한 후 동일한 자료형의 컬렉션을 반환하는 역할을 맡는 메서드

#### 1. map(), foreach()
- 형식: 
   - map(): map[B](f: (A) => B): List[B]
   - foreach(): foreach(f: (A) => Unit): Unit
- 원소 변형
```scala
val o = List(1,2,3,4)
# List(1,2,3,4)

val n = o.map(i => i * 10) or o.map( _ * 10)
# List(10,20,30,40)

o.foreach(i=> i*10)
```

#### 2. filter(), filterNot()
- 형식
   - filter(): filter(p: (A) => boolean) : List(A)
   - filterNot(): filterNot(p: (A) => boolean) : List(A)
- 필터링
- filterNot : 필터 반대
```scala
val o = List(1,2,3,4)
val n = o.filter(i => i >=3).map(i => i*2)
# List(6,8)
```

#### 3. foldLeft(), foldRight()
- 형식
   - foldLeft(): foldLeft[B](z: B)(f: (B, A) => B): B
   - foldRight(): foldRight[B](z: B)(op: (A, B) => B): B
- javascript의 reduce, reduceRight와 비슷한 기능

``` scala
val o = List(1,2,3,4)
val n = o.foldLeft(0)((i , j) => i + j)
# 10
```

#### 5. partition()
- 형식: partiotion(p: (A) => Boolean): (List[A], List[A])
- 조건에 맞는것, 맞지 않는것 두개로 분리
```scala
val o = List(1,2,3,4)
val n = o.partition(i => i <3)
(List(1,2),List(3,4))
```

#### 5. :::(), zip(), unzip()
- 형식
   - :::() : :::(prefix: List[A]): List[A]
   - zip[B](that: GenInterable[B]): List[(A,B)]
   - unzip[A1,A2)(implicit asPair: (A) => (A1,A2)): (List[A1], List[A2])
``` scala
val o = List(1, 2, 3, 4)
val oo = List(5, 6, 7, 8, 9)

val n = o zip oo
val nn = o ::: oo
val nnn = n.unzip

#List((1,5), (2,6), (3,7), (4,8))
#List(1, 2, 3, 4, 5, 6, 7, 8, 9)
#(List(1, 2, 3, 4),List(5, 6, 7, 8))
```
 
#### 6. find()
- 형식 : find(p: (A) => Boolean): Option[A]
- 조건에 맞는 첫번째 요소 반환(결과값은 Option 객체)
```scala
val o = List(1, 2, 3, 4)

val n = o.find(i => i >= 2)
val nn = o.find(i => i == 9)

# Some(2)
# None
```

#### 7. drop(), dropWhile()
- 형식
   - drop(): drop(n: Int): List[A]
   - dropWhile(p: (A) => Boolean): List[A]
- drop(): 해당 인덱스까지 모든 요소를 버림(until)
- dropWhile(): 조건에 맞을때까지 루프를 돌면서 요소를 버림.(조건이 맞는 순간 기능 멈춤)
```scala
val o = List(1, 2, 3, 4, 5, 6, 0)

val n = o.drop(4)
val nn = o.dropWhile(i => i < 3)

# List(5,6,0)
# List(3,4,5,6,0)
```

#### 8. flattern()
- 형식: flatten[B]: List[B]
- java의 flatmap과 비슷
```scala
val o = List(List(1, 2, 3, 4), List(5, 6))
val n = o.flatten

# List(1 ,2,3,4,5,6)
```
