### ISSUE TITLE
[함수형 프로그래밍] Chapter2.스칼라로 함수형 프로그래밍 시작하기

### ISSUE THREAD

**Issue by duckcalf** [NMP-Study/FunctionalProgrammingInScala#9]

**Comment by fairsun** [comment]
## 2.1 스칼라 언어이 소개 : 에제 하나

~~~scala
object MyModule {
  def abs(n: Int): Int =
    if (n < 0) -n
    else n

  private def formatAbs(x: Int) = {
    val msg = "the absolute value of %d id %d"
    msg.format(x, abs(x))
  }

  def main(args: Array[String]): Unit =
    println(formatAbs(-42))
}
~~~

### object 키워드
- singleton
- java : 익명 클래스의 새 인스턴스
- scala는 java의 static 키워드에 해당하는 것이 없으며 java에서 정적 멤버를 가진 클래스를 사용할 만한 상황일 때 사용

### def 키워드
- 좌변 : 서명
- 우변 : 정의
- 스칼라가 메서드의 반환 형식을 추론할 수 있는 경우가 많으며, 그럴 때에는 반환 형식을 생략할 수 있다.
- 하지만, 다른 사람이 사용할 메서드에서는 반환 형식을 명시적으로 지정해 주는 것이 좋은 코딩 습관이다.
- 문장 구분은 새 줄 또는 세미콜론으로 구분

### val  키워드
- 불변 변수

### main
- 순수 함수적 핵심부를 호출하고 그 결과를 콘솔에 출력하는 외부 계층이다.
- 부수 효과가 발생함을 강조하기 위해, 절차(=procedure) 또는 불순 함수(=impure function)라고 부른다.

### Unit
- java 의 void
- '유닛' 또는 '단위'라고 읽는다.
- 일반적으로, 반환 형식이 Unit이라는 것은 그 메서드에 부수 효과가 존재함을 암시한다.

## 2.2 프로그램의 실행
- REPL ( read-evaluate-print-loop)
    - 스칼라 해석기의 대화식 모드

## 2.3 모듈, 객체, 이름공간

### 이름공간
- MyModule은 abs가 속한 이름공간이다.

### 모듈
- 스칼라의 모든 값은 객체
- 각가의 객체는 0 또는 하나 이상의 멤버를 가질 수 있다. 
- 모듈(module) : 자신의 멤버들에게 이름공간을 제공하는 것이 주된 목적인 객체
- 멤버(member) :  def 키워드로 선언된 메서드, val 또는  object로 선언된 또 다른 객체, 기타 등등

### 표기법
- MyModule.abs(-42) : 이름 공간과 마침표 다음에 멤버의 이름을 지정
- 42.toString : 42라는 객체의 멤버 toString을 사용
- 2 + 1
    - 객체 2의 + 멤버를 호출하는 것 => 2.+(1) 에 대한 구문적 겉치레(syntactic sugar)
    - 스칼라에는 연산자라는 특별한 개념이 존재하지 않는다.
    - 인수가 하나인 메서드는 그 어떤 것이라도 마침표와 괄호를 생략한 중위(infix)표기법으로 호출 할 수 있다.
        - ex> MyModule abs -42
    - import 키워드 이용
        - import MyModule.abs or import MyModule._
        - abs(-42)
        
## 2.4 고차 함수: 함수를 함수에 전달

### 고차 함수(higher-order function, HOF)
- 다른 함수를 인수로 받는 함수

### 2.4.1 잠깐 곁가지: 함수적으로 루프 작성하기
- 꼬리 호출 : 재귀 호출의 결과를 그대로 돌려주는 것 외에는 아무 일도 하지 않은 호출
~~~scala
  def factorial(n: Int): Int = {
    @annotation.tailrec
    def go(n: Int, acc: Int): Int = {
      if (n <= 0) acc
      else go(n - 1, n * acc)

    }

    go(n, 1)
  }
~~~ 
- go(n - 1, n * acc) -> 꼬리 호출 O
- 1 + go(n - 1, n * acc) <- 꼬리 호출 X

#### 꼬리 호출 제거(tail call elimination)
- 재귀 호출의 반환 이후에 특별히 더 하는 일이 없다.
- 재귀를 매 반복마다 호출 스택을 소비하지 않는 반복 루프 형태로 컴파일한다.
- @tailrec : 꼬리 호츨 제거에 실패했을 때 스칼라 컴파일러가 컴파일 오류를 발생한다.

#### 연습문제 2.1
- n번째 피보나치 수를 돌려주는 재귀 함수를 작성하라.
- 처음 두 피보나치 수는 0과 1이다.
- n번째 피보나치 수는 항상 이전 두 수의 합이다. ( 0, 1, 1, 2, 3, 5)
- 지역 꼬리 재귀 함수를 사용해서 작성할 것.
- 정답 : [01.answer.scala](https://github.com/fpinscala/fpinscala/blob/7a43335a04679e140c8c4cf7c359fd8a39bbe39f/answerkey/gettingstarted/01.answer.scala)
~~~scala
  def fib(n: Int): Int = {
    @tailrec
    def go(n: Int, acc1: Int, acc2: Int): Int = {
      if (n == 0) acc1
      else go(n - 1, acc2, acc1 + acc2)
    }

    go(n, 0, 1)
  }
~~~

**Comment by fairsun** [comment]
## 2.5 다형적 함수: 형식에 대한 추상

#### 단형적 함수(monomorphic fuction)
- 한 형식의 자료에만 작용하는 함수
- abs와 factorial: Int 형식의 인수에만 특화
- formatResult : Int 형식의 인수를 받는 함수에만 작용하도록 고정

#### 다형적 함수(polymorphic function)
- 임의의 형식에 대해 작동하는 코드

### 2.5.1 다형적 함수의 예

#### 배열에서 문자열을 찾는 단형적 함수

~~~scala
  def findFirst(ss: Array[String], key: String): Int = {
    @annotation.tailrec
    def loop(n: Int): Int =
      if (n >= ss.length) -1
      else if (ss(n) == key) n
      else loop(n + 1)

    loop(0)
  }
~~~

### 배열에서 한 요소를 찾는 다형적 함수
- 일반적 함수(generic function)
- 형식에 대한 추상(abstracting over the type)을 배열과 배열 안의 한 요소를 검색하는 함수에 적용한 결과
~~~scala
  def findFirst[A](as: Array[A], p: A => Boolean): Int = {
    @annotation.tailrec
    def loop(n: Int): Int =
      if (n >= as.length) -1
      else if (p(as(n))) n
      else loop(n + 1)

    loop(0)
  }

    val array = Array("1", "2", "3")
    val key = "1"

    def isContain(item: String): Boolean = {
      item == key
    }

    val result = findFirst(array, isContain)
~~~
- 형식 매개변수(type parameter) : [A,B,C] 와 같은 짦은 한 글자짜리 대문자 형식으로 표현(관례)

#### 연습문제 2.2
- Array[A]가 주어진 비교 함수에 의거해서 정렬되어 있는지 점검하는 isSorted함수를 구현
- def isSorted[A](as: Array[A], ordered: (A, A) => Boolean): Boolean

~~~scala
  def isSorted[A](as: Array[A], ordered: (A, A) => Boolean): Boolean = {
    @annotation.tailrec
    def go(n: Int): Boolean =
      if (n >= as.length - 1) true
      else if (ordered(as(n), as(n + 1))) false
      else go(n + 1)

    go(0)
  }

  val array = Array(1, 2, 3, 4)
  def ordered(a: Int, b: Int): Boolean = {
    if (a <= b) false
    else true
  }

  val result = isSorted(array, ordered)
  println(result)
~~~

### 2.5.2 익명 함수로 고차 함수 호출

~~~scala
findFirst(Array(7,9,13), (x: Int) => x == 9)
~~~
- 배열 리터럴(array literal) : Array(7,9,13)
- 함수 리터럴(function literal) or 익명 함수(anonymous function) :  (x: Int) => x == 9

~~~sh
scala> (x: Int, y: Int) => x == y
res1: (Int, Int) => Boolean = $$Lambda$832/0x0000000801640840@2404b5a

scala> (x: Int, y: Int) => x < y
res2: (Int, Int) => Boolean = $$Lambda$833/0x0000000801641840@55acec99
~~~

> 스칼라에서 값으로서의 함수
>> 함수 리터럴을 정의할 때 실제로 정의되는 것은 apply 라는 메서드를 가진 하나의 객체
>> "함수는 일급(first-class)값이다" => 일급 함수 => 함수
>> https://www.scala-lang.org/api/current/scala/Function2.html
>~~~scala
> val lessThan = new Function2[Int, Int, Boolean] {
>      def apply(a: Int, b: Int) = a < b
>
>    }
>    println(lessThan(10, 20))
>~~~
> 

## 2.6 형식에서 도출된 구현

#### 부분 적용(partial application)
- 단 한 가지 방식으로만 구현할 수 있는 함수
~~~scala
def partial1[A, B, C](a: A, f: (A, B) => C) : B => C
~~~
- A, B, C : 세 개의 형식 매개 변수
- partial1은 a, f 두 개의 인수를 받는다.
- 인수 f : A,B 두 개의 인수를 받고 C를 리턴한다.
- partital1은 B => C 함수를 리턴한다.

~~~scala
def partial1[A, B, C](a: A, f: (A, B) => C) : B => C =
    (b: B) => f(a, b)
~~~

#### 연습문제 2.3
- https://github.com/fpinscala/fpinscala/blob/7a43335a04679e140c8c4cf7c359fd8a39bbe39f/answerkey/gettingstarted/03.answer.scala
~~~scala
def curry[A, B, C](f:(A, B) => C): A => (B => C) =
    (a: A) => (b: B) => f(a,b)
~~~
#### 연습문제 2.4
- https://github.com/fpinscala/fpinscala/blob/7a43335a04679e140c8c4cf7c359fd8a39bbe39f/answerkey/gettingstarted/04.answer.scala
~~~scala
def uncurry[A, B, C](f: A=> B=> C) : (A, B) => C =
    (a: A, b: B) => f(a)(b)
~~~

#### 함수 합성
- 한 함수의 출력이 다른 함수의 입력
#### 연습문제 2.5
- https://github.com/fpinscala/fpinscala/blob/7a43335a04679e140c8c4cf7c359fd8a39bbe39f/answerkey/gettingstarted/05.answer.scala
~~~scala
def compose[A, B, C](f: B => C, g: A=> B): A => C =
    (a: A) => f(g(a))
~~~
- https://www.scala-lang.org/api/current/scala/Function1.html
- f compose g  = g andThen f
